// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoahrthruljrxniasldg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvYWhydGhydWxqcnhuaWFzbGRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MzY1OTksImV4cCI6MjA2MTAxMjU5OX0.ode0mUq-ViGItVAyJjaGatRDhTQ5UjobJQNweLMRncA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);